# version: "3.9"

# services:
#   backend:
#     build:
#       context: ./backend
#       dockerfile: Dockerfile
#     container_name: fastapi-backend
#     env_file:
#       - ./backend/.env
#     ports:
#       - "127.0.0.1:8000:8000"
#     restart: unless-stopped

#   frontend:
#     build:
#       context: ./sportbet
#       dockerfile: Dockerfile
#       args:
#         NUXT_PUBLIC_backend_api: "http://backend:8000/api"
#     container_name: nuxt-frontend
#     environment:
#       - NUXT_PUBLIC_backend_api=http://backend:8000/api
#     ports:
#       - "127.0.0.1:3080:3080"
#     depends_on:
#       - backend
#     restart: unless-stopped

version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fastapi-backend
    env_file:
      - ./backend/.env
    # **CORRECTION**: Removed "127.0.0.1". This binds the container's port 8000
    # to the VPS's public IP on port 8000.
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build:
      context: ./sportbet
      dockerfile: Dockerfile
      args:
        NUXT_PUBLIC_backend_api: "http://backend:8000/api"
    container_name: nuxt-frontend
    environment:
      - NUXT_PUBLIC_backend_api=http://backend:8000/api
    # **CORRECTION**: Removed "127.0.0.1". This binds the container's port 3080
    # to the VPS's public IP on port 3080.
    ports:
      - "3080:3080"
    depends_on:
      - backend
    restart: unless-stopped
